name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js 18.x for front-end
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install dependencies for front-end
        run: |
          cd realgram-frontend
          npm install

      - name: Build front-end
        run: |
          cd realgram-frontend
          npm run vercel-build
          npm i -g vercel
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod

      - name: Set up Node.js 14.x for back-end
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies for back-end
        run: |
          cd realgram-backend
          npm install

      - name: Run tests for back-end
        run: |
          cd realgram-backend
          npm test

      - name: Deploy back-end
        run: |
          cd realgram-backend
          npm i -g vercel
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
